---
kind: pipeline
name: rustfmt

steps:
- name: rustfmt
  image: rust:latest
  commands:
    - rustup component add rustfmt
    - cargo fmt -- --check
- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: pipeline
name: test

depends_on:
- rustfmt

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --recursive --init
- name: test
  image: rust:latest
  pull: always
  environment:
    RUST_BACKTRACE: 1
    GIT_AUTHOR_EMAIL: drone@exqa.de
    GIT_AUTHOR_NAME: drone
  commands:
  - apt-get update && apt-get install -y libgtk-3-dev cmake meson
  - meson _build
  - ninja -C _build
  - ninja -C _build test

- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: signature
hmac: 97c8494db0d0014bf724d22bb87996c0ec36dcd03e9d37d237b62d8303385dd7

...
